# Generated by Django 4.2.16 on 2024-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsystem', '0002_alter_contact_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Mark this as resolved when the query is handled.'),
        ),
    ]
