# Generated by Django 4.2.16 on 2024-11-19 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM'), ('16:30', '4:30 PM'), ('17:00', '5:00 PM'), ('17:30', '5:30 PM'), ('18:00', '6:00 PM'), ('18:30', '6:30 PM'), ('19:00', '7:00 PM'), ('19:30', '7:30 PM'), ('20:00', '8:00 PM'), ('20:30', '8:30 PM'), ('21:00', '9:00 PM'), ('21:30', '9:30 PM'), ('22:00', '10:00 PM')], max_length=5)),
                ('guests', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
