# Generated by Django 4.2.16 on 2024-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_alter_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Jane', max_length=100),
            preserve_default=False,
        ),
    ]
