# Generated by Django 4.2.16 on 2024-12-16 20:40

import bookingsystem.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^\\+?1?\\d{9,15}$'), bookingsystem.models.validate_min_length]),
        ),
    ]
